// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: http.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartupReportRequest_HostType int32

const (
	StartupReportRequest_UNKNOWN    StartupReportRequest_HostType = 0
	StartupReportRequest_SELF       StartupReportRequest_HostType = 1
	StartupReportRequest_ALIYUN     StartupReportRequest_HostType = 2
	StartupReportRequest_TENCENTYUN StartupReportRequest_HostType = 3
)

// Enum value maps for StartupReportRequest_HostType.
var (
	StartupReportRequest_HostType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SELF",
		2: "ALIYUN",
		3: "TENCENTYUN",
	}
	StartupReportRequest_HostType_value = map[string]int32{
		"UNKNOWN":    0,
		"SELF":       1,
		"ALIYUN":     2,
		"TENCENTYUN": 3,
	}
)

func (x StartupReportRequest_HostType) Enum() *StartupReportRequest_HostType {
	p := new(StartupReportRequest_HostType)
	*p = x
	return p
}

func (x StartupReportRequest_HostType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartupReportRequest_HostType) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[0].Descriptor()
}

func (StartupReportRequest_HostType) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[0]
}

func (x StartupReportRequest_HostType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartupReportRequest_HostType.Descriptor instead.
func (StartupReportRequest_HostType) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{4, 0}
}

type StartupReportRequest_DBType int32

const (
	StartupReportRequest_MYSQL   StartupReportRequest_DBType = 0
	StartupReportRequest_TIDB    StartupReportRequest_DBType = 1
	StartupReportRequest_REDIS   StartupReportRequest_DBType = 2
	StartupReportRequest_MONGODB StartupReportRequest_DBType = 3
)

// Enum value maps for StartupReportRequest_DBType.
var (
	StartupReportRequest_DBType_name = map[int32]string{
		0: "MYSQL",
		1: "TIDB",
		2: "REDIS",
		3: "MONGODB",
	}
	StartupReportRequest_DBType_value = map[string]int32{
		"MYSQL":   0,
		"TIDB":    1,
		"REDIS":   2,
		"MONGODB": 3,
	}
)

func (x StartupReportRequest_DBType) Enum() *StartupReportRequest_DBType {
	p := new(StartupReportRequest_DBType)
	*p = x
	return p
}

func (x StartupReportRequest_DBType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartupReportRequest_DBType) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[1].Descriptor()
}

func (StartupReportRequest_DBType) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[1]
}

func (x StartupReportRequest_DBType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartupReportRequest_DBType.Descriptor instead.
func (StartupReportRequest_DBType) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{4, 1}
}

type HelloWorldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping *string `protobuf:"bytes,1,opt,name=ping,proto3,oneof" json:"ping,omitempty"`
}

func (x *HelloWorldRequest) Reset() {
	*x = HelloWorldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldRequest) ProtoMessage() {}

func (x *HelloWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldRequest.ProtoReflect.Descriptor instead.
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorldRequest) GetPing() string {
	if x != nil && x.Ping != nil {
		return *x.Ping
	}
	return ""
}

type HelloWorldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pang string `protobuf:"bytes,1,opt,name=pang,proto3" json:"pang,omitempty"`
}

func (x *HelloWorldResponse) Reset() {
	*x = HelloWorldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldResponse) ProtoMessage() {}

func (x *HelloWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldResponse.ProtoReflect.Descriptor instead.
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorldResponse) GetPang() string {
	if x != nil {
		return x.Pang
	}
	return ""
}

// heartbeat protocol
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentInfo *HeartbeatRequest_Agent `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	DbInfo    *HeartbeatRequest_DB    `protobuf:"bytes,2,opt,name=dbInfo,proto3" json:"dbInfo,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentInfo() *HeartbeatRequest_Agent {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetDbInfo() *HeartbeatRequest_DB {
	if x != nil {
		return x.DbInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{3}
}

// startup reporter protocol
type StartupReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostType      StartupReportRequest_HostType `protobuf:"varint,1,opt,name=host_type,json=hostType,proto3,enum=api.StartupReportRequest_HostType" json:"host_type,omitempty"`
	Hostname      string                        `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DbType        StartupReportRequest_DBType   `protobuf:"varint,3,opt,name=db_type,json=dbType,proto3,enum=api.StartupReportRequest_DBType" json:"db_type,omitempty"`
	DbVersion     string                        `protobuf:"bytes,4,opt,name=db_version,json=dbVersion,proto3" json:"db_version,omitempty"`
	IpAddr        string                        `protobuf:"bytes,5,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Port          int32                         `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Os            string                        `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                        `protobuf:"bytes,9,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	KernelVersion string                        `protobuf:"bytes,10,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Env           string                        `protobuf:"bytes,11,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *StartupReportRequest) Reset() {
	*x = StartupReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartupReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupReportRequest) ProtoMessage() {}

func (x *StartupReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupReportRequest.ProtoReflect.Descriptor instead.
func (*StartupReportRequest) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{4}
}

func (x *StartupReportRequest) GetHostType() StartupReportRequest_HostType {
	if x != nil {
		return x.HostType
	}
	return StartupReportRequest_UNKNOWN
}

func (x *StartupReportRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StartupReportRequest) GetDbType() StartupReportRequest_DBType {
	if x != nil {
		return x.DbType
	}
	return StartupReportRequest_MYSQL
}

func (x *StartupReportRequest) GetDbVersion() string {
	if x != nil {
		return x.DbVersion
	}
	return ""
}

func (x *StartupReportRequest) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *StartupReportRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartupReportRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *StartupReportRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *StartupReportRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *StartupReportRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type StartupReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartupReportResponse) Reset() {
	*x = StartupReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartupReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupReportResponse) ProtoMessage() {}

func (x *StartupReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupReportResponse.ProtoReflect.Descriptor instead.
func (*StartupReportResponse) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{5}
}

type HeartbeatRequest_Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Localip  string  `protobuf:"bytes,1,opt,name=localip,proto3" json:"localip,omitempty"`
	CpuRate  float64 `protobuf:"fixed64,2,opt,name=cpu_rate,json=cpuRate,proto3" json:"cpu_rate,omitempty"`
	DiskRate float64 `protobuf:"fixed64,3,opt,name=disk_rate,json=diskRate,proto3" json:"disk_rate,omitempty"`
	MemRate  float64 `protobuf:"fixed64,4,opt,name=mem_rate,json=memRate,proto3" json:"mem_rate,omitempty"`
}

func (x *HeartbeatRequest_Agent) Reset() {
	*x = HeartbeatRequest_Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest_Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest_Agent) ProtoMessage() {}

func (x *HeartbeatRequest_Agent) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest_Agent.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest_Agent) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{2, 0}
}

func (x *HeartbeatRequest_Agent) GetLocalip() string {
	if x != nil {
		return x.Localip
	}
	return ""
}

func (x *HeartbeatRequest_Agent) GetCpuRate() float64 {
	if x != nil {
		return x.CpuRate
	}
	return 0
}

func (x *HeartbeatRequest_Agent) GetDiskRate() float64 {
	if x != nil {
		return x.DiskRate
	}
	return 0
}

func (x *HeartbeatRequest_Agent) GetMemRate() float64 {
	if x != nil {
		return x.MemRate
	}
	return 0
}

type HeartbeatRequest_DB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dbtype string  `protobuf:"bytes,1,opt,name=dbtype,proto3" json:"dbtype,omitempty"`
	Port   int32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Qps    float64 `protobuf:"fixed64,3,opt,name=qps,proto3" json:"qps,omitempty"`
	Tps    float64 `protobuf:"fixed64,4,opt,name=tps,proto3" json:"tps,omitempty"`
}

func (x *HeartbeatRequest_DB) Reset() {
	*x = HeartbeatRequest_DB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest_DB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest_DB) ProtoMessage() {}

func (x *HeartbeatRequest_DB) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest_DB.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest_DB) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{2, 1}
}

func (x *HeartbeatRequest_DB) GetDbtype() string {
	if x != nil {
		return x.Dbtype
	}
	return ""
}

func (x *HeartbeatRequest_DB) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HeartbeatRequest_DB) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *HeartbeatRequest_DB) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

var File_http_proto protoreflect.FileDescriptor

var file_http_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x35, 0x0a, 0x11, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x28, 0x0a, 0x12, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x6e, 0x67, 0x22, 0xcc, 0x02, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x06, 0x64, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x42, 0x52, 0x06, 0x64,
	0x62, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x74, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x63, 0x70, 0x75, 0x52,
	0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x52, 0x61, 0x74, 0x65, 0x1a, 0x54, 0x0a, 0x02, 0x44,
	0x42, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x62, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x71, 0x70, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x74, 0x70,
	0x73, 0x22, 0x13, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd8, 0x03, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3f, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x07,
	0x64, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x42, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x06, 0x64, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x62, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x62, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6b, 0x65, 0x72, 0x6e,
	0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x3d, 0x0a, 0x08, 0x48,
	0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x4c, 0x49, 0x59, 0x55, 0x4e, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45,
	0x4e, 0x43, 0x45, 0x4e, 0x54, 0x59, 0x55, 0x4e, 0x10, 0x03, 0x22, 0x35, 0x0a, 0x06, 0x44, 0x42,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x54, 0x49, 0x44, 0x42, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x44,
	0x49, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x4f, 0x4e, 0x47, 0x4f, 0x44, 0x42, 0x10,
	0x03, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_proto_rawDescOnce sync.Once
	file_http_proto_rawDescData = file_http_proto_rawDesc
)

func file_http_proto_rawDescGZIP() []byte {
	file_http_proto_rawDescOnce.Do(func() {
		file_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_proto_rawDescData)
	})
	return file_http_proto_rawDescData
}

var file_http_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_http_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_http_proto_goTypes = []interface{}{
	(StartupReportRequest_HostType)(0), // 0: api.StartupReportRequest.HostType
	(StartupReportRequest_DBType)(0),   // 1: api.StartupReportRequest.DBType
	(*HelloWorldRequest)(nil),          // 2: api.HelloWorldRequest
	(*HelloWorldResponse)(nil),         // 3: api.HelloWorldResponse
	(*HeartbeatRequest)(nil),           // 4: api.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 5: api.HeartbeatResponse
	(*StartupReportRequest)(nil),       // 6: api.StartupReportRequest
	(*StartupReportResponse)(nil),      // 7: api.StartupReportResponse
	(*HeartbeatRequest_Agent)(nil),     // 8: api.HeartbeatRequest.Agent
	(*HeartbeatRequest_DB)(nil),        // 9: api.HeartbeatRequest.DB
}
var file_http_proto_depIdxs = []int32{
	8, // 0: api.HeartbeatRequest.agent_info:type_name -> api.HeartbeatRequest.Agent
	9, // 1: api.HeartbeatRequest.dbInfo:type_name -> api.HeartbeatRequest.DB
	0, // 2: api.StartupReportRequest.host_type:type_name -> api.StartupReportRequest.HostType
	1, // 3: api.StartupReportRequest.db_type:type_name -> api.StartupReportRequest.DBType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_http_proto_init() }
func file_http_proto_init() {
	if File_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloWorldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartupReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartupReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest_Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest_DB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_http_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_proto_goTypes,
		DependencyIndexes: file_http_proto_depIdxs,
		EnumInfos:         file_http_proto_enumTypes,
		MessageInfos:      file_http_proto_msgTypes,
	}.Build()
	File_http_proto = out.File
	file_http_proto_rawDesc = nil
	file_http_proto_goTypes = nil
	file_http_proto_depIdxs = nil
}
