// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.0

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type HttpServiceHTTPServer interface {
	Hello(context.Context, *HelloWorldRequest) (*HelloWorldResponse, error)
}

func RegisterHttpServiceHTTPServer(s *http.Server, srv HttpServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/hello_world", _HttpService_Hello0_HTTP_Handler(srv))
}

func _HttpService_Hello0_HTTP_Handler(srv HttpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloWorldRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.HttpService/Hello")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hello(ctx, req.(*HelloWorldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloWorldResponse)
		return ctx.Result(200, reply)
	}
}

type HttpServiceHTTPClient interface {
	Hello(ctx context.Context, req *HelloWorldRequest, opts ...http.CallOption) (rsp *HelloWorldResponse, err error)
}

type HttpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHttpServiceHTTPClient(client *http.Client) HttpServiceHTTPClient {
	return &HttpServiceHTTPClientImpl{client}
}

func (c *HttpServiceHTTPClientImpl) Hello(ctx context.Context, in *HelloWorldRequest, opts ...http.CallOption) (*HelloWorldResponse, error) {
	var out HelloWorldResponse
	pattern := "/hello_world"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.HttpService/Hello"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
